package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"log"

	"github.com/99designs/gqlgen/graphql"
	"github.com/schema-creator/graph-gateway/src/graph/model"
	"github.com/schema-creator/graph-gateway/src/internal"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string) (*model.User, error) {
	txn := r.App.StartTransaction("CreateUser")
	defer txn.End()
	res, err := r.UserService.CreateUser(ctx, name)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, userID string, name *string) (*model.User, error) {
	return nil, fmt.Errorf("not implemented: UpdateUser - updateUser")
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*model.User, error) {
	return nil, fmt.Errorf("not implemented: DeleteUser - deleteUser")
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, title string) (*model.Project, error) {
	txn := r.App.StartTransaction("CreateProject")
	defer txn.End()
	res, err := r.ProjectService.CreateProject(ctx, title)
	if err != nil {
		log.Println(err)
		return nil, err
	}

	return res, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, projectID string, title *string, lastImage *graphql.Upload) (*model.Project, error) {
	txn := r.App.StartTransaction("UpdateProject")
	defer txn.End()
	res, err := r.ProjectService.UpdateProject(ctx, projectID, *title, lastImage)
	if err != nil {
		log.Println(err)
		return nil, err
	}

	return res, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, projectID string) (*string, error) {
	txn := r.App.StartTransaction("DeleteProject")
	defer txn.End()
	res, err := r.ProjectService.DeleteProject(ctx, projectID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// CreateInviteLink is the resolver for the createInviteLink field.
func (r *mutationResolver) CreateInviteLink(ctx context.Context, projectID string, authority model.Auth) (*string, error) {
	txn := r.App.StartTransaction("CreateInviteLink")
	defer txn.End()
	res, err := r.ProjectService.CreateInviteLink(ctx, projectID, authority)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// CreateProjectMember is the resolver for the createProjectMember field.
func (r *mutationResolver) CreateProjectMember(ctx context.Context, token string) (*model.ProjectMember, error) {
	txn := r.App.StartTransaction("CreateProjectMember")
	defer txn.End()
	res, err := r.MemberService.CreateMember(ctx, token)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// UpdateProjectMember is the resolver for the updateProjectMember field.
func (r *mutationResolver) UpdateProjectMember(ctx context.Context, projectID string, userID string, authority *model.Auth) (*model.ProjectMember, error) {
	txn := r.App.StartTransaction("UpdateProjectMember")
	defer txn.End()
	res, err := r.MemberService.UpdateMember(ctx, projectID, userID, authority)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// DeleteProjectMember is the resolver for the deleteProjectMember field.
func (r *mutationResolver) DeleteProjectMember(ctx context.Context, projectID string, userID string) (*string, error) {
	txn := r.App.StartTransaction("DeleteProjectMember")
	defer txn.End()

	res, err := r.MemberService.DeleteMember(ctx, projectID, userID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	txn := r.App.StartTransaction("User")
	defer txn.End()
	res, err := r.UserService.GetUser(ctx, userID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, projectID string) (*model.Project, error) {
	txn := r.App.StartTransaction("Project")
	defer txn.End()

	res, err := r.ProjectService.GetProject(ctx, projectID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, userID string) ([]*model.Project, error) {
	txn := r.App.StartTransaction("Projects")
	defer txn.End()
	res, err := r.ProjectService.GetProjects(ctx, userID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// ProjectMembers is the resolver for the projectMembers field.
func (r *queryResolver) ProjectMembers(ctx context.Context, projectID string) ([]*model.ProjectMember, error) {
	txn := r.App.StartTransaction("ProjectMembers")
	defer txn.End()
	res, err := r.MemberService.GetMembers(ctx, projectID)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return res, nil
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
