name: Generate types from Schema Docs to the frontend

on:
  push:
    branches:
      - develop
    paths:
      - 'cmd/schema/**'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup npm version 18
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      # install required packages
      - name: Install graphql codegen
        run: |
          npm i -g @graphql-codegen/cli \
            @graphql-codegen/typescript \
            @graphql-codegen/typescript-operations \
            @graphql-codegen/typescript-react-apollo \
            @graphql-codegen/typescript-resolvers

      - name: Generate types from schema
        run: |
          cd cmd/schema
          mkdir -p codegen
          npm run codegen
          cp -r codegen/* $HOME/schema
    
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: Hack-Hack-geek-Vol10/frontend
          token: ${{ secrets.GH_PAT }}
          ref: develop
              
      # switch repository to frontend
      - name: copy item to frontend
        run: |
          git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
          git config --global user.name "${{ secrets.USERNAME_GITHUB }}"

          git switch -c ft/codegen${{github.sha}}

          mkdir -p codegen
          cp -r $HOME/schema/* codegen
          
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "feat: generate types from schema"
          git push origin ft/codegen${{github.sha}}

      - name: create Pull Request to frontend
        run: |
          gh pr create \
            --title ":robot: generated openAPI schema[bot]" \
            --body ":robot: generated openAPI schema[bot]" \
            --repo Hack-Hack-geek-Vol10/frontend \
            --base develop \
            --head ft/codegen${{github.sha}} \
            --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}